ARG py_version=3.11.2

FROM python:$py_version-slim-bullseye AS base

USER root
RUN apt-get update \
  && apt-get dist-upgrade -y \
  && apt-get install -y --no-install-recommends \
    build-essential=12.9 \
    ca-certificates=20210119 \
    git=1:2.30.2-1+deb11u2 \
    libpq-dev=13.21-0+deb11u1 \
    make=4.3-4.1 \
    openssh-client=1:8.4p1-5+deb11u3 \
    software-properties-common=0.96.20.2-2.1 \
  && apt-get clean \
  && rm -rf \
    /var/lib/apt/lists/* \
    /tmp/* \
    /var/tmp/*

RUN mkdir /usr/app/ /usr/app/.dbt/
WORKDIR /usr/app/
RUN useradd -d /usr/app -u 1000 -g 0 dbt
RUN chown -R :0 /usr/app/
RUN chmod -R 770 /usr/app/
ENV PYTHONIOENCODING=utf-8
ENV LANG=C.UTF-8

RUN python -m pip install --upgrade "pip==24.0" "setuptools==69.2.0" "wheel==0.43.0" --no-cache-dir

CMD [ "/bin/bash" ]

FROM base AS dbt-core
USER root
ARG commit_ref=main

HEALTHCHECK CMD dbt --version || exit 1

RUN python -m pip install --no-cache-dir "dbt-core @ git+https://github.com/dbt-labs/dbt-core@${commit_ref}#subdirectory=core"
USER dbt

# dbt for local postgres 

FROM dbt-core AS dbt-postgres
USER root
ARG commit_ref=main

HEALTHCHECK CMD dbt --version || exit 1

RUN python -m pip install --no-cache-dir "dbt-postgres @ git+https://github.com/dbt-labs/dbt-adapters@${commit_ref}#subdirectory=dbt-postgres"
USER dbt

# dbt for bigquery

FROM dbt-core AS dbt-bigquery
USER root
ARG commit_ref=main

HEALTHCHECK CMD dbt --version || exit 1

COPY ./google_cred/google-credentials.json /.google/credentials/google-credentials.json
RUN python -m pip install --no-cache-dir "dbt-bigquery @ git+https://github.com/dbt-labs/dbt-adapters@${commit_ref}#subdirectory=dbt-bigquery"
USER dbt