services:
  dbt-bigquery:
    build: 
      context: ..
      dockerfile: ./dbt/dockerfile
      target: dbt-bigquery

    env_file: './.env'
    volumes:
      - ./project:/usr/app/project
      - ./.dbt/profiles.yml:/usr/app/.dbt/profiles.yml

    stdin_open: true  
    tty: true        
