FROM apache/airflow:latest-python3.12

ENV AIRFLOW_HOME=/opt/airflow

USER airflow
COPY ./airflow/requirements.txt .
COPY ./google_cred /opt/airflow/google
USER root
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
         vim \
  && apt-get autoremove -yqq --purge \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
USER airflow
RUN pip install --no-cache-dir apache-airflow==${AIRFLOW_VERSION} -r requirements.txt

WORKDIR $AIRFLOW_HOME
