FROM apache/airflow:latest-python3.9

ENV AIRFLOW_HOME=/opt/airflow

USER airflow
COPY requirements.txt .
USER root
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
         vim \
  && apt-get autoremove -yqq --purge \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
USER airflow
RUN pip install --no-cache-dir apache-airflow==${AIRFLOW_VERSION} -r requirements.txt

WORKDIR $AIRFLOW_HOME
COPY ../google /opt/airflow/google