dbt-bigquery-profile:
  target: dev 
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('DATASET_NAME') }}"
      threads: 4
      priority: interactive
      keyfile: /.google/credentials/google-credentials.json
      location: US